version: "3"

services:
  db:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: security
      MYSQL_ROOT_PASSWORD: s@f3_p@55
    healthcheck:
      test: mysqladmin ping -h localhost --user=root --password=s@f3_p@55
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
        - security_network
volumes:
  mysql-data:
networks:
  security_network:
    driver: bridge